language:
  - objective-c

env:
  matrix:
    - TEST='macpython27_10.9'
    - TEST='macpython33_10.9'

    - TEST='brew_system'
    - TEST='brew_system' VENV='1'

    - TEST='brew_py'
    - TEST='brew_py' VENV='1'

    - TEST='brew_py3'
    - TEST='brew_py3' VENV='1'

    - TEST='macports' PY='2.6'
    - TEST='macports' PY='2.6' VENV='1'

    - TEST='macports_py27'
    - TEST='macports_py27' VENV='1'

    - TEST='macports' PY='3.2'
    - TEST='macports' PY='3.2' VENV='1'

    - TEST='macports_py33'
    - TEST='macports_py33' VENV='1'

install:
  - set -vx  # echo commands
  - source ./install.sh

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../test.sh

after_failure:
  - echo $PWD
