language: 
  - objective-c
  - erlang

env:
  - PYTHON=python PYSUF='' PYVER=2.6
  - PYTHON=python PYSUF='' PYVER=2.7

install:
  - sudo apt-get update
  - sudo apt-get install $PYTHON-numpy
  - sudo apt-get install $PYTHON-nose

script:
  - nosetests .
