language:
  - objective-c

env:
  matrix:
    - TEST='macpython_10.9' PY_VERSION=2.7.5
    - TEST='macpython_10.9' PY_VERSION=3.3.5
    - TEST='macpython_10.9' PY_VERSION=3.4.0

    - TEST='brew_system'
    - TEST='brew_system' VENV='1'

    - TEST='brew_py' PY="2.7"
    - TEST='brew_py' PY="2.7" VENV='1'

    - TEST='brew_py' PY="3.3"
    - TEST='brew_py' PY="3.3" VENV='1'

    - TEST='macports' PY='2.7'
    - TEST='macports' PY='2.7' VENV='1'

    - TEST='macports' PY='3.3'
    - TEST='macports' PY='3.3' VENV='1'

    - TEST='macports' PY='3.4'
    - TEST='macports' PY='3.4' VENV='1'

install:
  - set -vx  # echo commands
  - source ./install.sh

script:
  - echo $PWD
  - mkdir tmp_test_dir
  - cd tmp_test_dir
  - source ../test.sh

after_failure:
  - echo $PWD
