language: 
  - objective-c

env:
  - TEST='macpython27_10.8'
  - TEST='macpython27_10.8' BIN_NUMPY='1'
  - TEST='macpython33_10.8'
# no python 3 numpy installer
#   - TEST='macpython33_10.8' BIN_NUMPY='1'

  - TEST='brew_system'
  - TEST='brew_system' VENV='1'

  - TEST='brew_py'
  - TEST='brew_py' VENV='1'

  - TEST='brew_py3'
  - TEST='brew_py3' VENV='1'

  - TEST='macports_py26'
  - TEST='macports_py26' VENV='1'

  - TEST='macports_py27'
  - TEST='macports_py27' VENV='1'

  - TEST='macports_py32'
  - TEST='macports_py32' VENV='1'

  - TEST='macports_py33'
  - TEST='macports_py33' VENV='1'


install:
  - set -x  # echo commands
  - source ./install.sh

script:
  - source ./test.sh
