language: 
  - objective-c

env:
  - TEST='macpython27_10.8_numpy'
  - TEST='macpython27_10.8'
  - TEST='macpython33_10.8'
  - TEST='brew_system'
  - TEST='brew_py'
  - TEST='brew_py3'
  - TEST='macports_py26'
  - TEST='macports_py27'
  - TEST='macports_py32'
  - TEST='macports_py33'

install:
  - source ./install.sh

script:
  - source ./test.sh
