language: 
  - objective-c

env:
  - TEST='brew_system'  PYTHON=python
  - TEST='brew_py'      PYTHON=python
  - TEST='brew_py3'     PYTHON=python3

install:
  - sh ./install_brew.sh

script:
  - nosetests .
