language: 
  - objective-c

# os:
#   macos

# env:
#   - PYTHON=python PYSUF='' PYVER=2.6
#   - PYTHON=python PYSUF='' PYVER=2.7

install:
  - brew update
  - brew install python freetype
  - pip install numpy
  - brew install pkg-config
  - pip install matplotlib

script:
  - nosetests .
