language: 
  - objective-c

env:
  - PYTHON=python PYSUF='' PYVER=2.6
#   - PYTHON=python PYSUF='' PYVER=2.7

install:
  - sudo brew update
  - sudo brew install python freetype
  - sudo brew install python-numpy
  - sudo pip install numpy

script:
  - nosetests .
